---
title: "Pteridaceae occurance data"
author: "Sylvia Kinosian"
output: html_document
---

Plotting Pteridacae from Testo & Sundue (2016) 4k tree
```{r}
library(ape)
library(phytools)

# Bring in 4k tree
fern_tree.4k <- read.nexus("4k.tre")

# prune to just Pteridaceae and some outgroups
pteridaceaeClade <- getMRCA(fern_tree.4k, tip = c("Coniogramme_wilsonii", "Pteris_altissima"))

# extract this node to make sure its right.
pteridaceaeClade.tre <- extract.clade(fern_tree.4k, pteridaceaeClade)

# look at how many species are in the taxa
length(pteridaceaeClade.tre$tip.label)
# 589

plotTree(pteridaceaeClade.tre,ftype="i",cex=0.6, fsize=0.4, offset=1, type="fan")

# write.tree
#write.tree(pteridaceaeClade.tre, "pteridaceaeClade.tre")
```

Code from Will Pearse: "Programming for Biologists" course

Occurance data & predictions
```{r}
library(raster)

# Download data
r <- getData("worldclim",var="bio",res=10)

# Give the variables some more sensible names
names(r) <- c("temp.mean","diurnal.range", "isothermality",
"temp.season","max.temp","min.temp","temp.range","temp.wettest",
"temp.driest","temp.mean.warmest","temp.mean.coldest","precip",
"precip.wettest","precip.driest","precip.season","precip.wettest",
"precip.driest","precip.warmest","precip.coldest")

# Plot it out
plot(r)

# If you wanted to subset your data to only some parts of the world,
# this would be the part to change
e <- extent(-170,170,-60,60)

# Grab all of this out in data.frame format, if you wish
data <- data.frame(na.omit(extract(r, e)))

# Load package
library(rgbif)

# Download occurence data for a the Pteridaceae family (limiting the fields we grab)
# takes maybe an hour to run
# what is limit?
pter <- occ_search(scientificName = "Pteridaceae",
fields=c("name", "decimalLatitude", "decimalLongitude"),
limit = 1000, return = "data")

# Plot this ~informatively
plot(r[[1]])
with(pter, points(decimalLatitude ~ decimalLongitude, pch = 20, cex = 0.5))

# Load package
library(sp)

# Remove parts of our pter occurrences with no actual data
# (GBIF has data of variable quality, and we're not filtering it)
pter <- na.omit(pter)

# Make a spatial points object from our pter data
# ~ x + y
point.pter <- pter
coordinates(point.pter) <- ~decimalLongitude+decimalLatitude

# Extract the data
pter$mean.temp <- extract(r[[1]], point.pter)
pter$precip <- extract(r[[12]], point.pter)

# Load strangely-named package
library(e1071)

# Fit model
model <- svm(pter$mean.temp, type="one")

# Make a raster to store predictions
pred.raster <- r[[1]]

# Predict from our model
# - ignoring oceans (NAs)
values(pred.raster)[!is.na(values(pred.raster))] <-
predict(model, Filter(Negate(is.na), values(pred.raster)))

# Plot where it's predicted to be
plot(pred.raster)
```
